apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vault-argocd-watcher.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault-argocd-watcher.labels" . | nindent 4 }}
